Traceback (most recent call last):
  File "run.py", line 43, in parse
    output = subprocess.run(cmd,stdout = subprocess.PIPE,stderr = subprocess.PIPE,shell=True,check=False,timeout=1800,text=True)
  File "/home//.conda/envs/py38/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home//.conda/envs/py38/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home//.conda/envs/py38/lib/python3.8/subprocess.py", line 1885, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/home//.conda/envs/py38/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '/bdata2/ca_new/smartbugs/smartbugs -t oyente -f /bdata2/sc/dataset/mainnet/0xda3ae7a56aeb73d7b9a255172ae99bf66551a9dc.sol  --mem-limit 4g --timeout 1200  --solcv 0.8.7 --json' timed out after 1800 seconds

