mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/python3.8/lib/python3.8/site-packages/mythril/interfaces/cli.py", line 968, in parse_args_and_execute
    execute_command(
  File "/home/amax/anaconda3/envs/python3.8/lib/python3.8/site-packages/mythril/interfaces/cli.py", line 869, in execute_command
    "json": report.as_json(),
  File "/home/amax/anaconda3/envs/python3.8/lib/python3.8/site-packages/mythril/analysis/report.py", line 299, in as_json
    return json.dumps(result, sort_keys=True)
  File "/home/amax/anaconda3/envs/python3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/amax/anaconda3/envs/python3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/amax/anaconda3/envs/python3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/amax/anaconda3/envs/python3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

