{25148: 0}
{25148: 0.3327100882306695}
{25148: 0.34513260005041957}
{25148: 0.3487649718299508}
{25148: 0.6810389207676053}
{25148: 1.095602106768638}
{25148: 1.4812511685304344}
{25148: 1.9575686897151172}
{25148: 2.374142272863537}
{25148: 2.5888248938135803}
{25148: 2.9616983039304614}
{25148: 3.15138754574582}
{25148: 3.4689870150759816}
{25148: 3.6667137281037867}
{25148: 4.020079729147255}
{25148: 4.244278806261718}
{25148: 5.073667508549988}
{25148: 8247.66198892286}
{25148: 8248.050637913868}
{25148: 22032.641233886126}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'STATICCALL'
