{19119: 0}
{19119: 0.5328794098459184}
{19119: 0.5515050478279591}
{19119: 0.5574597679078579}
{19119: 1.0923113278113306}
{19119: 1.748908344656229}
{19119: 2.373042790684849}
{19119: 3.0570212258026004}
{19119: 3.726812058594078}
{19119: 4.321431535296142}
{19119: 5.024599783588201}
{19119: 5.726654655300081}
{19119: 6.383163013029844}
{19119: 6.692468069959432}
{19119: 7.177266485057771}
{19119: 7.561848610639572}
{19119: 8.132825340609998}
{19119: 8.436741875484586}
{19119: 8.976164475549012}
{19119: 9.310690600425005}
{19119: 9.8577132653445}
{19119: 10.19500921946019}
{19119: 10.201187290716916}
{19119: 10.539674322120845}
{19119: 10.54577195411548}
{19119: 12183.339127107058}
{19119: 12183.511980344076}
{19119: 20049.38714634301}
{19119: 31768.59146660706}
{19119: 31768.815051706973}
{19119: 31768.818947839085}
{19119: 31769.287900088355}
{19119: 31769.69494886743}
{19119: 31770.233210428152}
{19119: 31770.23715267796}
{19119: 31770.776282872073}
{19119: 31770.780162137}
{19119: 32391.915744594764}
{19119: 32392.821937070694}
{19119: 37477.19530503871}
{19119: 44893.878122923896}
{19119: 48159.51388985105}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'STATICCALL'
