{33764: 0}
{33764: 0.3362721321173012}
{33764: 0.3492286028340459}
{33764: 0.35323268081992865}
{33764: 0.6909817340783775}
{33764: 1.1173201790079474}
{33764: 1.5077295959927142}
{33764: 1.9478952679783106}
{33764: 2.3786021848209202}
{33764: 2.7887689508497715}
{33764: 3.252175065688789}
{33764: 3.675771194510162}
{33764: 4.104942596517503}
{33764: 4.346899637486786}
{33764: 4.690362234599888}
{33764: 4.908258276525885}
{33764: 5.2832740703597665}
{33764: 5.465502756182104}
{33764: 5.797483867034316}
{33764: 6.011446151416749}
{33764: 6.303971155546606}
{33764: 13705.088481845334}
{33764: 13705.387510264292}
{33764: 13706.304464403074}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'STATICCALL'
