{25936: 0}
{25936: 0.5654382901266217}
{25936: 0.5856930902227759}
{25936: 0.5923785092309117}
{25936: 1.1562318401411176}
{25936: 1.8552733231335878}
{25936: 2.5045259720645845}
{25936: 3.229948886204511}
{25936: 3.9412570488639176}
{25936: 4.5802778587676585}
{25936: 5.3341676774434745}
{25936: 5.704113757237792}
{25936: 6.32495418516919}
{25936: 6.626308460254222}
{25936: 7.36225819028914}
{25936: 7.6789280185475945}
{25936: 8.28756074886769}
{25936: 8.680594911798835}
{25936: 9.259431080892682}
{25936: 9.634539949707687}
{25936: 10.672564562875777}
{25936: 11.06272980151698}
{25936: 11.069430458825082}
{25936: 3610.2454714979976}
{25936: 3700.3033757968806}
{25936: 4050.7625957778655}
{25936: 5912.96684901882}
{25936: 5913.203046690673}
{25936: 5913.444530146662}
{25936: 5913.682583316695}
{25936: 5914.160391221754}
{25936: 5914.388169254642}
{25936: 5914.869134253357}
{25936: 5915.036079559475}
{25936: 5915.427329270635}
{25936: 5915.718031985685}
{25936: 5915.722620469518}
{25936: 5916.767895329278}
{25936: 5917.303969917353}
{25936: 5917.941380798351}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 845, in run
    ret = func(s, *funcarg)
  File "/ssd//tools/git/RA/vm.py", line 1401, in op_sha3
    data = str(simplify(data))
UnboundLocalError: local variable 'data' referenced before assignment
