{23591: 0}
{23591: 0.3333608200773597}
{23591: 0.34565764712169766}
{23591: 0.34929349087178707}
{23591: 0.6831909758038819}
{23591: 1.100210206117481}
{23591: 1.4951881989836693}
{23591: 1.7725833468139172}
{23591: 2.1803746996447444}
{23591: 2.3672414724715054}
{23591: 2.695455855689943}
{23591: 2.871410426683724}
{23591: 3.219139290973544}
{23591: 3.4493984733708203}
{23591: 3.8071009661071002}
{23591: 4.0551090631634}
{23591: 5.054352013859898}
{23591: 5.287599139846861}
{23591: 5.29119250876829}
{23591: 5929.79982909793}
{23591: 5930.203588902019}
{23591: 10446.349614360835}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'STATICCALL'
