{2857: 0}
{2857: 0.592606517020613}
{2857: 0.6137236068025231}
{2857: 0.6210558246821165}
{2857: 1.210494828876108}
{2857: 1.956202844157815}
{2857: 2.6720799752511084}
{2857: 3.544688383117318}
{2857: 4.295632878318429}
{2857: 5.073619739618152}
{2857: 5.893477057572454}
{2857: 6.265770800411701}
{2857: 6.882739951834083}
{2857: 7.269028813578188}
{2857: 7.9823581404052675}
{2857: 8.316608185414225}
{2857: 8.910922706127167}
{2857: 9.326226616743952}
{2857: 9.914226362947375}
{2857: 10.308379611931741}
{2857: 10.861093512736261}
{2857: 11.301086413674057}
{2857: 13.457093912176788}
{2857: 14.007317373063415}
{2857: 14.01466428115964}
{2857: 4102.812194407918}
{2857: 17035.99527865788}
{2857: 17036.611213427503}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'STATICCALL'
