{2292: 0}
{2292: 0.5316973561421037}
{2292: 0.5499661481007934}
{2292: 0.5557890040799975}
{2292: 1.1106314579956234}
{2292: 1.8226100313477218}
{2292: 2.5082939732819796}
{2292: 3.2251726891845465}
{2292: 3.9215535763651133}
{2292: 4.539485354442149}
{2292: 5.217486783396453}
{2292: 5.919128147419542}
{2292: 6.5672998442314565}
{2292: 6.884795520454645}
{2292: 7.413931140676141}
{2292: 7.730285274796188}
{2292: 8.305585348978639}
{2292: 8.592316830996424}
{2292: 9.107187256682664}
{2292: 9.441509925760329}
{2292: 9.94748810166493}
{2292: 10.283146808389574}
{2292: 10.289569001179188}
{2292: 10.624247489031404}
{2292: 10.630295080132782}
{2292: 11.565352164208889}
{2292: 13.551262712106109}
{2292: 7176.069023117423}
{2292: 7176.568195243366}
{2292: 10317.830064218491}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'STATICCALL'
