{34401: 0}
{34401: 0.006459951866418123}
{34401: 0.01276850188151002}
{34401: 0.0226800418458879}
{34401: 0.031861130613833666}
{34401: 0.05284179141744971}
{34401: 0.06203830847516656}
{34401: 0.0761512340977788}
{34401: 0.08546906104311347}
{34401: 0.10239634569734335}
{34401: 0.11176754860207438}
{34401: 0.15452721761539578}
{34401: 0.16403559083119035}
{34401: 0.20140477176755667}
{34401: 0.21100009372457862}
{34401: 0.24206889467313886}
{34401: 0.26738423854112625}
{34401: 0.3073990596458316}
{34401: 0.329298825468868}
{34401: 0.8303679465316236}
{34401: 0.9462756696157157}
{34401: 6590.1291584516875}
{34401: 6590.9085984095}
{34401: 9563.557706995402}
{34401: 9564.752320953645}
{34401: 11566.083230504766}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'STATICCALL'
