Traceback (most recent call last):
  File "__main__.py", line 286, in <module>
    main()
  File "__main__.py", line 277, in main
    matches.extend(pattern.find_matches())
  File "/bdata2//tools/securify/master/securify2/securify/analyses/patterns/static/static_analysis_patterns.py", line 73, in find_matches
    static = analysis_context.static_analysis
  File "/bdata2//tools/securify/master/securify2/securify/analyses/analysis.py", line 88, in static_analysis
    self._static = self.config.static_analysis(self)
  File "__main__.py", line 255, in <lambda>
    static_analysis=lambda t: static_analysis.analyze_cfg(t.cfg, **souffle_config),
  File "/bdata2//tools/securify/master/securify2/securify/staticanalysis/static_analysis.py", line 124, in analyze_cfg
    souffle_kwargs=kw_args_souffle)
  File "/bdata2//tools/securify/master/securify2/securify/staticanalysis/souffle/souffle.py", line 51, in run_souffle
    fact_dir = get_dir(fact_dir)
  File "/bdata2//tools/securify/master/securify2/securify/staticanalysis/souffle/souffle.py", line 43, in get_dir
    shutil.rmtree(d)
  File "/home//.conda/envs/securify2/lib/python3.7/shutil.py", line 498, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home//.conda/envs/securify2/lib/python3.7/shutil.py", line 496, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/bdata2//tools/securify/master/securify2/securify/staticanalysis/facts_in'
